import Head from "next/head";

import { type NextPage } from "next";

import React from "react";
import { useRouter } from "next/router";

const Error: NextPage<{ statusCode: number | undefined }> = ({
  statusCode,
}) => {
  const router = useRouter();

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full w-full flex-col items-start justify-start gap-2 p-6 sm:w-4/12">
        <header className="mb-4 mt-8">
          <h1 className="text-4xl font-bold tracking-tight text-white ">
            Oups - {statusCode}
          </h1>
          <p className="mt-2 text-gray-400">
            Mais qu&apos;est ce que vous faites là ?
          </p>
        </header>
        <div className="flex h-full w-full flex-col justify-center gap-4">
          <p>Un problème est survenu, vous allez redirectionner sous peu.</p>
          <p>Si ce n&apos;est pas le cas, appuyez sur le bouton si dessous </p>
        </div>
        <button
          onClick={async () => await router.push("/")}
          className="mt-10 flex w-full items-center justify-center gap-2 rounded-md bg-white py-3 font-bold text-black disabled:opacity-50"
        >
          Retour à l&apos;accueil
        </button>
      </main>
    </>
  );
};

Error.getInitialProps = ({ res, err }) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404;
  return { statusCode };
};

export default Error;
